baseURL = "http://lisemoxolll.dk/kea/public/"
languageCode = "en-us-da"
title = "Moxoll Theme"
theme = "systematik"


[[menu.main]]

name= "Home"
title= "Home section"
weight= "1"
indentifier="home"
url="/"

[[menu.main]]

name= "Guide"
title= "Guide"
weight= "2"
indentifier="dokumentation"
url="/dokumentation/"

[[menu.main]]

name= "Contact"
title= "Contact"
weight= "3"
indentifier="contact"
url="../contact"





